services:
  postgres-service:
    container_name: pgsql
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: demo_db
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgres/data
    networks:
      - spring-boot-network

  spring-boot-app:
    container_name: spring-demo
    image: docklearn
    ports:
      - "8088:8080"
    networks:
      - spring-boot-network
    depends_on:
      - postgres-service

volumes:
  postgres:

networks:
  spring-boot-network:
    driver: bridge